stages:
  - test
  - package
  - deploy

cargo_test:
  stage: test
  tags:
    - virt_host
  script: cargo test

cargo_deb:
  stage: package
  tags:
    - virt_host
  script:
    - cargo install cargo-deb
    - cargo deb --package tcp-chat
  artifacts:
    paths:
      - ./target/debian/tcp-chat_0.1.0-1_amd64.deb

# dpkg_install:
#   stage: deploy
#   tags:
#     - virt_host
#   script:
#     - dpkg --install ./target/debian/tcp-chat_0.1.0-1_amd64.deb
