stages:
  - test
  - deploy

cargo_test:
  tags:
    - virt_host
  stage: test
  script: cargo test

cargo_deb:
  tags:
    - virt_host
  stage: test
  script:
    - cargo install cargo-deb
    - cargo deb --package tcp-chat
  artifacts:
    paths:
      - ./target/debian/tcp-chat_0.1.0-1_amd64.deb
