version: "3.8"

services:
    postgresql:
        image: postgres:16
        hostname: ${POSTGRES_HOST}
        restart: unless-stopped
        env_file:
            - .envrc
        volumes:
            - postgresql-data:/var/lib/postgresql/data
        ports:
            - "${PGPORT}:${PGPORT}"

    sqlrunner:
        build:
            context: .
            dockerfile: sqlrunner/Dockerfile
        env_file:
            - .envrc
        environment:
            DATABASE_URL: ${DOCKER_DATABASE_URL}
        depends_on:
            - postgresql

    server:
        build:
            context: .
            dockerfile: server/Dockerfile
        restart: unless-stopped
        env_file:
            - .envrc
        environment:
            DATABASE_URL: ${DOCKER_DATABASE_URL}
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        depends_on:
            - postgresql
            - sqlrunner

    pgadmin:
        image: elestio/pgadmin:latest
        restart: unless-stopped
        env_file:
            - .envrc
        ports:
            - "${PGADMIN_PORT}:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgresql

volumes:
    postgresql-data:
    pgadmin-data:
