// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServersideRoomEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomUuid *UUID `protobuf:"bytes,1,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	// Types that are assignable to Event:
	//	*ServersideRoomEvent_NewMessage
	Event isServersideRoomEvent_Event `protobuf_oneof:"event"`
}

func (x *ServersideRoomEvent) Reset() {
	*x = ServersideRoomEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServersideRoomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersideRoomEvent) ProtoMessage() {}

func (x *ServersideRoomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersideRoomEvent.ProtoReflect.Descriptor instead.
func (*ServersideRoomEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *ServersideRoomEvent) GetRoomUuid() *UUID {
	if x != nil {
		return x.RoomUuid
	}
	return nil
}

func (m *ServersideRoomEvent) GetEvent() isServersideRoomEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *ServersideRoomEvent) GetNewMessage() *ServersideMessage {
	if x, ok := x.GetEvent().(*ServersideRoomEvent_NewMessage); ok {
		return x.NewMessage
	}
	return nil
}

type isServersideRoomEvent_Event interface {
	isServersideRoomEvent_Event()
}

type ServersideRoomEvent_NewMessage struct {
	// Someone sent a new message in this chat room.
	NewMessage *ServersideMessage `protobuf:"bytes,2,opt,name=new_message,json=newMessage,proto3,oneof"`
}

func (*ServersideRoomEvent_NewMessage) isServersideRoomEvent_Event() {}

type ServersideUserEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserUuid *UUID `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	// Types that are assignable to Event:
	//	*ServersideUserEvent_AddedToRoom
	Event isServersideUserEvent_Event `protobuf_oneof:"event"`
}

func (x *ServersideUserEvent) Reset() {
	*x = ServersideUserEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServersideUserEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersideUserEvent) ProtoMessage() {}

func (x *ServersideUserEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersideUserEvent.ProtoReflect.Descriptor instead.
func (*ServersideUserEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *ServersideUserEvent) GetUserUuid() *UUID {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (m *ServersideUserEvent) GetEvent() isServersideUserEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *ServersideUserEvent) GetAddedToRoom() *UUID {
	if x, ok := x.GetEvent().(*ServersideUserEvent_AddedToRoom); ok {
		return x.AddedToRoom
	}
	return nil
}

type isServersideUserEvent_Event interface {
	isServersideUserEvent_Event()
}

type ServersideUserEvent_AddedToRoom struct {
	AddedToRoom *UUID `protobuf:"bytes,2,opt,name=added_to_room,json=addedToRoom,proto3,oneof"` // UUID kicked_from_room = 3;
}

func (*ServersideUserEvent_AddedToRoom) isServersideUserEvent_Event() {}

var File_events_proto protoreflect.FileDescriptor

var file_events_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x74, 0x63, 0x70, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x1a, 0x0e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x64, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x2b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x63, 0x70, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x55,
	0x55, 0x49, 0x44, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x55, 0x75, 0x69, 0x64, 0x12, 0x3e, 0x0a,
	0x0b, 0x6e, 0x65, 0x77, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x63, 0x70, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x73, 0x69, 0x64, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x00, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x07, 0x0a,
	0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x81, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x64, 0x65, 0x55, 0x73, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2b,
	0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x63, 0x70, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x55, 0x55, 0x49,
	0x44, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x0d, 0x61,
	0x64, 0x64, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x63, 0x70, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x55, 0x55,
	0x49, 0x44, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x64, 0x64, 0x65, 0x64, 0x54, 0x6f, 0x52, 0x6f, 0x6f,
	0x6d, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f,
	0x62, 0x62, 0x2d, 0x68, 0x61, 0x63, 0x6b, 0x61, 0x74, 0x68, 0x6f, 0x6e, 0x2f, 0x74, 0x63, 0x70,
	0x2d, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x67, 0x69, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData = file_events_proto_rawDesc
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_events_proto_rawDescData)
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_proto_goTypes = []interface{}{
	(*ServersideRoomEvent)(nil), // 0: tcp_chat.ServersideRoomEvent
	(*ServersideUserEvent)(nil), // 1: tcp_chat.ServersideUserEvent
	(*UUID)(nil),                // 2: tcp_chat.UUID
	(*ServersideMessage)(nil),   // 3: tcp_chat.ServersideMessage
}
var file_events_proto_depIdxs = []int32{
	2, // 0: tcp_chat.ServersideRoomEvent.room_uuid:type_name -> tcp_chat.UUID
	3, // 1: tcp_chat.ServersideRoomEvent.new_message:type_name -> tcp_chat.ServersideMessage
	2, // 2: tcp_chat.ServersideUserEvent.user_uuid:type_name -> tcp_chat.UUID
	2, // 3: tcp_chat.ServersideUserEvent.added_to_room:type_name -> tcp_chat.UUID
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_entities_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServersideRoomEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServersideUserEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_events_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ServersideRoomEvent_NewMessage)(nil),
	}
	file_events_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ServersideUserEvent_AddedToRoom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_rawDesc = nil
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
