name: Rust check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  SERVER_RPC_PORT: 9001
  POSTGRESQL_PORT: 9002
  PGADMIN_PORT: 9003

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose
